apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl: 
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:  
    - image: achubsl/shrink-it-user
      context: user-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: achubsl/shrink-it-gateway
      context: gateway-dev
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '/**/*.ts'
            dest: .
    - image: achubsl/shrink-it-shrinkurl
      context: shrinkurl-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '/**/*.ts'
            dest: .