apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.podName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.podName }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.podName }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3003
              protocol: TCP
          env:
            - name: MONGO_URI
              value: mongodb://shrinkurl-mongo-srv:27017/shrinkurl
     