apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-depl
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: achubsl/shrink-it-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-srv
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - name: gateway
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31500
  