apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: achubsl/shrink-it-user
---
apiVersion: v1
kind: Service
metadata: 
  name: user-srv
spec:
  selector:
    app: user
  ports:
    - name: user
      protocol: TCP
      port: 3000
      targetPort: 3000